### ISSUE TITLE
(Possible) Issue with “Profit value (pips) to move SL to breakeven” in v1.05

### ISSUE THREAD

**Issue by muchgeneric** [EarnForex/Account-Protector#1]
Hello,
Thank you so much for this amazing EA!

I've been using it for the past few weeks.

“Profit value (pips) to start trailing SL” and “Trailing SL value (pips)” seem to be working as expected.
However, either there is an issue with “Profit value (pips) to move SL to breakeven” or I don't understand it right:

When I trade US30 and set this value to 500, I expect that once my profit gets to 500 pips my SL would be set to 0.
Is that correct?
However, instead of this, my SL gets set to -500 and I get kicked out right away with any slight movement of the price not in my direction.

Here are my trades from today, which I was originally placing with a 1,000-pip (point) TP and a 3,000-pip SL, but was getting kicked out with 500 pips in profit:
![image](https://user-images.githubusercontent.com/91504035/134992053-b540bd1a-78b6-45f6-9454-aaf200d37eae.png)

My Account Protector settings:
![image](https://user-images.githubusercontent.com/91504035/134992277-f030e851-bc4c-491d-887e-f4a672a7f432.png)

Can you please let me know whether I'm misunderstanding this setting or whether there is an actual issue with it?

**Comment by EarnForex** [comment]
Hello!

It looks like it is applying the "Breakeven extra profit value (pips)" even when you don't have the checkbox checked.

Thanks for reporting this!

**Comment by EarnForex** [comment]
Fixed in 1.06.

**Comment by muchgeneric** [comment]
Fix verified. Thank you!
