### ISSUE TITLE
Export settings

### ISSUE THREAD

**Issue by davideciarmiello** [EarnForex/Account-Protector#10]
Hi.
is possible to export and after import all settings? 
if export presets, not export internal settings.
Thanks

**Comment by EarnForex** [comment]
Hello!

No, there is no export/import option for the panel's settings if that's what you are asking about.

**Comment by davideciarmiello** [comment]
Yes is my question.
Viewed in code that settings are saved
but if i close chart  and recreate it, i can't use same settings.
m_FileName = "AP_" + IntegerToString(ChartID()) + ".txt";
it's possibile to make variable filename as input paramater, and if empty to set a default value?
Thus it will be possible to easily save and re-import the settings.
Thanks!

**Comment by EarnForex** [comment]
OK, I might consider adding this in the next version.

**Comment by davideciarmiello** [comment]
ok. if you would, i have managed it and other two features (DelayClosePlatform and CloseAllOtherChartsFiltered) on my fork.

**Comment by EarnForex** [comment]
Added in 1.10.
