### ISSUE TITLE
Ea not attaching to any chat

### ISSUE THREAD

**Issue by kushalmittal2001** [EarnForex/Account-Protector#5]
I am using MT4, I added the whole folder to the Expert folder. I'm using other EAs also, they are working.

In the Expert tab, I;m getting an error which says

2022.03.19 02:04:26.418	cannot open file 'c:\Program Files\MetaTrader 4\MQL4\Experts\Account Protector\Account Protector.ex4' [2]

**Comment by EarnForex** [comment]
Hello!

Try compiling Account Protector.mq4 in MetaEditor and let me know what it says.

**Comment by kushalmittal2001** [comment]
Nothing happens I tried.  I tried AutoTrading Scheduler too. Can you send me .EX4 file for both?

**Comment by kushalmittal2001** [comment]
<img width="815" alt="Screenshot 2022-03-19 at 2 19 10 AM" src="https://user-images.githubusercontent.com/61709365/159081181-0629ee32-b03a-45ae-a472-f831d5071f3c.png">

**Comment by kushalmittal2001** [comment]
I guess I'm using M1 Mac there for it's not compiling, please share .MQ4 files.

**Comment by kushalmittal2001** [comment]
I have managed to do it, it was due to M1 Mac, I complied is other laptop it worked. Thank you so much.
Just one just question, If I want to auto close orders after a timespan of 10 mins is that possible?

**Comment by EarnForex** [comment]
You can set a timer to 10 minutes in the future to close all orders after 10 minutes. But if you want that each order is closed at 10 minutes of its own lifetime, then you are out of luck - AP cannot do that.

By the way, next time you have trouble compiling an EA, you can download .ex4/.ex5 files from the Releases section on this GitHub repository.
