### ISSUE TITLE
Can you add a action to limit the number of open active trades when a certain filter condition is met?

### ISSUE THREAD

**Issue by RonLid** [EarnForex/Account-Protector#7]
I use v 1.07 with great satisfaction, but there are 2 issues that bother me:

1. I found that with certain EAs if there is a parameter that controls the MAX number of trades that the EA can open it can protect us from callout and margin calls. For example, if you make "MaxOrder" parameter = 2 in the Golden Elephant, this EA would not fail even during a large DD. However, when we do that the gains are limited when the market behaves well with minimal DDs. Also, most EAs don't have parameters that control this issue and for most EAs we don't have the source code. So is there a way, instead of turning off Autotrading at a free margin level of X (say 1000%), just to start limiting the number of new trades that can be opened to a certain number but not turning off Autotrading? If this is possible, when the free margin indicates impending peril, we could limit the risk but not shut off trading altogether.  The opposite could be also useful - open the full throttle above a certain condition.

2.  The other issue that bothers me is that we cannot activate the EA in a pending mode. Suppose I set up a condition and action - the EA would not do the job if there are no open trades.  For example, I mostly turn off auto trading below X free margin, but I can't set up the condition and action if there is no open trade. This requires me to periodically watch the EA and jump in to activate the action when the first trade is placed. This is a drag, because I may just miss an adverse action because of that. Also, if the EA closes all the trades with profits it triggers the action of Account Protector, and in the case above the Autotrade is turned off. This requires me to check periodically in order to reactivate the action when new trades are being placed. The lack of PENDING action that would remain active as long as a condition has not been met even if there are no active trades would make this excellent tool a superb one.

Thanks for considering - Yaron

**Comment by EarnForex** [comment]
Hello Yaron,

1. Unfortunately, there is no way for the AP to control how many trades some other EA can open. It could try closing all trades in excess of a certain number, but that would only lead to a disaster when an EA is constantly opening a new trade and the AP is closing it.
2. Sorry, but I don't understand what's the problem here... Why can't you set a free margin conditions + some actions when there are no open trades?

PS: Any specific reason you are using 1.07 and not 1.08?

**Comment by RonLid** [comment]
Thank for your reply. Very sorry that problem 1 is not solvable. With problem 2, when I set free margin condition + action (close Autotrading)  it activates the action (showing OK) if there are open trades but if there are no open trades the condition is triggered and the Autotrading is stopped. I have then to uncheck that action, manually reactivate Autotrading and wait for the EA to open some trades. I will switch to 1.08 over the weekend. Sent from Mail for Windows From: EarnForexSent: Wednesday, September 14, 2022 3:05 AMTo: EarnForex/Account-ProtectorCc: RonLid; AuthorSubject: Re: [EarnForex/Account-Protector] Can you add a action to limit the number of open active trades when a certain filter condition is met? (Issue #7) Hello Yaron,Unfortunately, there is no way for the AP to control how many trades some other EA can open. It could try closing all trades in excess of a certain number, but that would only lead to a disaster when an EA is constantly opening a new trade and the AP is closing it.Sorry, but I don't understand what's the problem here... Why can't you set a free margin conditions + some actions when there are no open trades?PS: Any specific reason you are using 1.07 and not 1.08?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by EarnForex** [comment]
What is the exact condition you are setting? It shouldn't be triggering just because there are no trades...

**Comment by RonLid** [comment]
Hello again, I replaced 1.07 with 1.08 and it’s even worse. Now if there are no trades the EA also setup the condition back to 0 in addition to triggering the action.I’m sending you a series of snapshots that show what I’m talking about:Snap #1: No trades, Free Margin 6,975, Autotrading=On, No condition, No action, Snap #2: No trades, Free Margin 6,975, Autotrading=On, Condition=Margin level <=% 1000, No action,Snap #3: No trades, Free Margin 6,975, Autotrading=On, Condition=Margin level <=% 1000, No action,Snap #4: No trades, Free Margin 6,975, I selected “Disable Autotrading” -> it triggered Autotrading off and unchecked the selectionSnap #5: : No trades, Free Margin 6,975, Autotrading=Off, it unchecked and erased the value of the Condition=Margin level <=%, No action, As I said, the EA doesn’t allow to set a condition and an action when there is no active trade. Version 1.07 just triggered the Autotrading off. Version 1.08 does that and also unchecking/erasing the condition. Can that be fixed? Thanks, Yaron  Sent from Mail for Windows From: EarnForexSent: Wednesday, September 14, 2022 4:42 AMTo: EarnForex/Account-ProtectorCc: RonLid; AuthorSubject: Re: [EarnForex/Account-Protector] Can you add a action to limit the number of open active trades when a certain filter condition is met? (Issue #7) What is the exact condition you are setting? It shouldn't be triggering just because there are no trades...—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by EarnForex** [comment]
Hello Yaron,

It looks like you are replying to this thread via email. This messes up the formatting of your responses and also doesn't allow me to see your image attachments. It would be better if you could post your response on GitHub.

**Comment by RonLid** [comment]
Thank you. Going to sleep right now. We'll copy what I sent you by email to Github when I'll wake up.

[Yaron Lidor - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1qduub)	[1qduub]

On September 18, 2022 at 6:31 GMT, EarnForex ***@***.***> wrote:

Hello Yaron,

It looks like you are replying to this thread via email. This messes up the formatting of your responses and also doesn't allow me to see your image attachments. It would be better if you could post your response on GitHub.

**Comment by RonLid** [comment]
The condition is when the “Margin Level <= %”  ->  disable autotrading. I may use free % margins between 2000% (multipair EAs) to 150%, but mostly 1000%, and when I set it up always the free margin is higher than the condition value. Sent from Mail for Windows From: EarnForexSent: Wednesday, September 14, 2022 4:42 AMTo: EarnForex/Account-ProtectorCc: RonLid; AuthorSubject: Re: [EarnForex/Account-Protector] Can you add a action to limit the number of open active trades when a certain filter condition is met? (Issue #7) What is the exact condition you are setting? It shouldn't be triggering just because there are no trades...—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by EarnForex** [comment]
Yes, Margin Level is 0% when you have no open trades. I will consider adding a check for open trades when Margin Level conditions are checked.

**Comment by RonLid** [comment]
Thank you for the reply. I would appreciate if you can arrange that your great and useful EA would work while it is awaiting for trades to kick in (i.e. in a special situation that the margin is less than the condition or it's zero, when it is set up by the trader). I was thinking to ask one of the MQL5 coders to do it as a paid job on their site. Their going rate for a job like that, that usually is completed in several hours, is $30-40. I would rather have you do it, as you know the ins/outs of this ES, so I'm ready to pay you. Please let me know if you get my offer and what is the expected turn around time. Thank you, Yaron.

[Yaron Lidor - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1rzji9)	[1rzji9]

On October 11, 2022 at 9:44 GMT, EarnForex ***@***.***> wrote:

Yes, Margin Level is 0% when you have no open trades. I will consider adding a check for open trades when Margin Level conditions are checked.

**Comment by EarnForex** [comment]
Sorry, but I don't do custom coding orders. This change _will_ be implemented, but this will be done in its own time and completely free of charge.

**Comment by RonLid** [comment]
Sorry to learn that you don't do custom coding. Do you have approximate
estimate when it will be implemented?

**Comment by EarnForex** [comment]
Was fixed back in 1.09.
