### ISSUE TITLE
Profit/Loss Calculations 

### ISSUE THREAD

**Issue by andrewazevedo10** [EarnForex/Account-Protector#8]
I have noticed when using both floating & daily profit/loss with either percent or currency value, that if I have an account that a deposit/withdrawal is made that these values are calculate into the those values. Example is if I want take profit to be at 1,000 and my current trade is at 200 in profit but I deposit 800 the Account Protector will automatically close out all trades since the floating/daily profit has been hit of 1,000. The only way around this is to disable the EA while I wait for my broker to deposit the funds then re-enable after. Is there a way to only calculate profit/loss for trade that are executed and not for deposits/withdrawals that are in the account history?

<img width="779" alt="Screenshot 2023-04-13 at 10 08 39 PM" src="https://user-images.githubusercontent.com/98892354/231924006-c7a3a8e6-88b2-43a3-b583-4ace20fe0766.png">
<img width="1895" alt="Screenshot 2023-04-13 at 10 12 07 PM" src="https://user-images.githubusercontent.com/98892354/231924447-a26ddcc9-dd75-429b-b7e3-cbfc5270bd11.png">

**Comment by EarnForex** [comment]
Thank you for reporting! I'll look into this and will try to fix it in the next version.

**Comment by EarnForex** [comment]
Should be fixed in 1.10.
