### ISSUE TITLE
Add Conditions Maximum  Open Trade

### ISSUE THREAD

**Issue by nnayakbbsr** [EarnForex/Account-Protector#9]
Sir Kindly add the conditions Maximum Buy Trade Open and Maximum Sell trade open.

**Comment by EarnForex** [comment]
Hello!

How would those conditions work?

**Comment by nnayakbbsr** [comment]
sir Suppose I am using some other EA. There is lot multiplier in it. So it opens more trades. If I set maximum open trdae then it will not open new order.

**Comment by nnayakbbsr** [comment]
sir i also check EA parameter, there are  one options (Use Total Volume: enable if trading with many small trades and pa)
after change the true option. not showing in check box.

**Comment by EarnForex** [comment]
OK, I will add a condition for the number of open trades/orders in the next version.

As for the Use Total Volume parameter, I don't understand the problem. Which checkbox are you expecting to see?

**Comment by EarnForex** [comment]
Added in 1.10.
